import type { Agent, AgentAction, AgentRun, EvidenceReceipt, RunEvent, TaskActionInput, TaskSuccessCondition } from "@/lib/agent-types";
import type { Contract, Membership } from "@/lib/types";
import { demoAction, demoAgent, demoEvidence, demoRun } from "@/lib/agent-demo-data";

export const agentFixture: Agent = { ...demoAgent, id: "agent-1", name: "Renewal assistant", organization_id: "org-1", delegated_by_user_id: "user-1", contract_ids: ["contract-1"], assignee_ids: ["user-1"], expires_at: "2099-12-01T00:00:00Z" };
export const runFixture: AgentRun & { success_condition: TaskSuccessCondition } = { ...demoRun, id: "run-1", organization_id: "org-1", agent_id: agentFixture.id, status: "awaiting_approval", result: {}, completed_at: null, deadline_at: "2099-11-01T00:00:00Z", success_condition: { type: "workspace_task_created", contract_id: "contract-1", assigned_to_user_id: "user-1", due_at: "2099-10-30T09:00:00Z" } };
export const actionFixture: AgentAction & { input: TaskActionInput & { description: string } } = { ...demoAction, id: "action-1", run_id: runFixture.id, status: "awaiting_approval", approval_status: "pending", approved_by_user_id: null, approval_reason: "", result: {}, completed_at: null, approval_expires_at: "2099-10-30T09:00:00Z", input: { title: "Review renewal notice deadline", description: "Confirm whether to renew before sending notice.", deadline_basis: null, contract_id: "contract-1", assigned_to_user_id: "user-1", evidence_id: "receipt-1", due_at: runFixture.success_condition.due_at } };
export const evidenceFixture: EvidenceReceipt = { ...demoEvidence, id: "receipt-1", contract_id: "contract-1", version_id: "version-1", excerpt: "This agreement renews unless written notice is given at least 30 days before renewal." };
export const eventFixture = (sequence: number): RunEvent => ({ id: `event-${sequence}`, run_id: runFixture.id, sequence, type: "test.event", data: {}, created_at: "2026-10-01T09:00:00Z" });
export const contractFixture: Contract = { id: "contract-1", organization_id: "org-1", title: "Retained supplier contract", source_name: "supplier.txt", counterparty: "Supplier", contract_type: "Agreement", status: "ready", review_context: {}, retain_document: false, retain_source_text: true, retention_days: 365, expires_at: "2099-12-01T00:00:00Z", created_at: "2026-10-01T09:00:00Z", updated_at: "2026-10-01T09:00:00Z", latest_job: null };
export const memberFixture: Membership = { id: "member-1", user_id: "user-1", email: "owner@example.test", display_name: "Workspace owner", role: "owner", created_at: "2026-10-01T09:00:00Z" };
