"use client";

import Link from "next/link";
import { BrandMark } from "../brand-mark";
import { useWorkspace } from "../workspace-provider";
import { canAdministerAgents } from "@/lib/agent-state";
import "./developer-guide.css";

const example = `import { LensLayerClient } from "@lenslayer/agent-sdk";

// Server only. Install the locally packed SDK; it is not published on npm.
const client = new LensLayerClient({
  baseUrl: process.env.LENSLAYER_API_URL,
  token: process.env.LENSLAYER_AGENT_TOKEN,
});
const run = await client.createRun(runInput); // explicit scope, dates, stable key
const evidence = await client.retrieveEvidence(run.id, {
  contract_id: contractId, query: "renewal notice",
});
const proposal = await client.proposeAction(run.id, {
  idempotency_key: actionKey, tool: "workspace.tasks.create",
  input: { contract_id: contractId, assigned_to_user_id: assigneeId,
    due_at: dueAt, evidence_id: evidence.id,
    title: "Review renewal notice deadline" },
});
// proposal accepted != task executed. Human approval stays outside this client.
const completed = await client.pollRun(run.id, {
  deadlineAt: run.deadline_at, timeoutMs: 300_000,
});`;

export function DeveloperGuide() {
  const { activeRole, isDemo, isLoading, error, activeOrganization, canUpload } = useWorkspace();
  const manage = canAdministerAgents(activeRole, isDemo);
  return <main className="developer-guide" id="developer-main">
    <header className="developer-nav"><BrandMark /><Link className="button secondary" href="/runs">Explore sample runs</Link><Link href="/signin">Sign in</Link></header>
    <div className="developer-intro"><h1>Build a verified follow-up.</h1><p>Assign an exact goal to LensLayer or bring your own server-side agent. Both use scoped evidence, human approval and read-back receipts. Calendar event workflows use the same ledger after consent; live provider verification remains a release step.</p><Link className="button secondary" href="/agent-tasks">{manage ? "Assign a hosted goal" : "Explore hosted task access"}</Link></div>
    <aside className="developer-notice" aria-label="Workspace access">
      {isLoading ? <p role="status">Checking workspace access. The guide is available while access loads.</p> : error ? <p role="alert">Workspace access could not be loaded. You can still read this guide; sign in again before provisioning a credential.</p> : isDemo || !activeOrganization ? <p>The public walkthrough is synthetic and read-only. <Link href="/signin">Sign in to a private workspace</Link> for real sources, credentials, and approvals.</p> : manage ? <p>You can provision scoped agents and resolve approvals in your active workspace. Verify the selected workspace before creating a credential.</p> : <p>Your role can inspect run records, but cannot create agent credentials or approve actions. Ask a workspace owner or administrator to delegate scope.</p>}
    </aside>
    <section className="developer-errors" aria-labelledby="hosted-guide-heading"><h2 id="hosted-guide-heading">Let LensLayer prepare the proposals</h2><p>Private workspace owners and administrators can use <Link href="/agent-tasks">Agent tasks</Link> to assign a document follow-up, a private Calendar event, or both. Supply the exact retained source, member, originally granted calendar, titles and times with an explicit timezone. The service creates an internal delegation limited to those facts and your execution deadline; no agent credential enters the browser.</p><p>Default planning is a fixed workflow with no model call. Optional model assistance appears only when enabled by the service and requires explicit acknowledgement that your goal, scoped facts and any retained excerpt will be shared with OpenAI GPT-6.1 Sol at high effort. Open the assignment’s run to supply requested facts, approve exact actions and inspect each verified receipt. Recorded, planning and approval states do not mean an effect exists. The external-client setup below uses the same ledger.</p></section>
    <nav className="developer-index" aria-label="Guide contents"><a href="#retain">1. Retain</a><a href="#scope">2. Scope</a><a href="#client">3. Run</a><a href="#approve">4. Inspect</a><a href="#verify">5. Verify</a></nav>
    <div className="developer-sequence">
      <section id="retain"><h2>1. Retain the source</h2><p>Upload an agreement with source-text retention enabled and wait for review extraction to finish. Record its contract ID and select an actual workspace member’s user ID. Missing assignees or factual dates require explicit input, not a model guess.</p><p>Retrieval uses a case-insensitive literal phrase of 2–200 characters. Receipts contain version IDs, extracted-text hashes, and offsets; excerpts are read from retained text on demand. Removing the source makes evidence unavailable.</p>{manage || (!isDemo && canUpload) ? <Link className="button secondary" href="/contracts/new">Upload a retained source</Link> : <Link className="button secondary" href="/contracts">Inspect sample sources</Link>}</section>
      <section id="scope"><h2>2. Delegate exact scope</h2><p>An owner or administrator opens Agents and selects the retained document, permitted assignee, <code>documents.retrieve</code> and <code>workspace.tasks.create</code>, a future expiry, and normally one action per run. Leave human approval enabled.</p><p>The bearer is shown once. Save it in a server-side secret manager, dismiss the display, and never put it in a prompt, browser storage, query cache, analytics, or a screenshot. Agent credentials cannot call human approval routes.</p><Link className="button secondary" href="/agents">{manage ? "Manage scoped agents" : "Inspect agent access"}</Link></section>
      <section id="client"><h2>3. Run an external client</h2><p>Start the existing FastAPI API and continuous worker. The agent owns planning; the worker owns dispatch. Use Node 20.3+ and build the local package before installing its tarball. No framework runtime dependency or npm publication is implied.</p><pre><code>{["npm --prefix sdk ci", "npm --prefix sdk run release:check", "npm --prefix sdk pack --pack-destination /your/private/package-directory", "# In a server-side client project:", "npm install /your/private/package-directory/lenslayer-agent-sdk-0.1.0.tgz"].join("\n")}</code></pre><p>Set the required server-side values using <code>examples/agents/.env.example</code>: contract, assignee, timezone-aware due instant, future run deadline within credential expiry, and persisted run/action keys. Then run:</p><pre><code>node --env-file=examples/agents/.env examples/agents/renewal-follow-up.mjs</code></pre><details><summary>SDK call sequence</summary><pre><code>{example}</code></pre><p>Define <code>runInput</code> with both allowed tools, one contract, one action, <code>deadline_at</code>, a stable <code>idempotency_key</code>, and <code>success_condition</code>: <code>workspace_task_created</code> with the exact contract, assignee, and due instant. The example supplies the complete runnable configuration.</p></details><p>For MCP, build <code>mcp/</code> and point your local host’s stdio configuration at <code>mcp/dist/stdio.js</code>, with server-side <code>LENSLAYER_API_URL</code> and <code>LENSLAYER_AGENT_TOKEN</code>. Only delegated capabilities are discovered. There is no hosted MCP URL or remote OAuth endpoint.</p><p>A bounded planner CLI also lives in <code>hosted-agent/</code>. It uses the same API and stops for input or human approval. Real product-model calls are separately opt-in; this CLI is a reference external client, separate from the database-backed hosted assignment service.</p></section>
      <section id="approve"><h2>4. Inspect and approve exact input</h2><p>Open the run printed by your client in the correct private workspace. Inspect its success condition, source version/hash, due instant, assignee, immutable action input/hash, and approval expiry. An owner or administrator approves or rejects with a reason. The proposal cannot be edited in place.</p><p>The window ends at the earlier of one hour after proposal or the run deadline. Expired approvals need a new reviewed run, not a silent retry. Keep the worker running during approval waits.</p><Link className="button secondary" href="/runs">Inspect runs</Link></section>
      <section id="verify"><h2>5. Check the verified receipt</h2><p>Only <code>succeeded</code> with <code>verified=true</code>, <code>verification_method=database_read_back</code>, and the expected task/source fields certifies task creation at completion. Check the task register and ordered events. A pending or queued proposal is not an executed action.</p><p>Restart with unchanged configuration and original keys; reuse the original action and evidence. Do not generate new keys after a timeout. Cancellation stops new dispatch but does not undo completed effects. A polling timeout does not cancel the server run.</p><Link className="button secondary" href="/tasks">Inspect tasks</Link></section>
    </div>
    <section className="developer-errors"><h2>Additive workflow contracts</h2><p>The additive API methods <code>createWorkflow</code> and <code>proposeToolAction</code> also support one private timed Google Calendar event or an <code>all</code> condition with named task/event entries. Delegate an exact OAuth connection/calendar pair; calendar-only scope needs no contract or assignee. A private workspace owner or administrator starts consent in <Link href="/settings#calendar-connection">Calendar settings</Link> and completes it on return as the same person. Configure the exact dashboard callback and provider/encryption secrets first; live consent/write checks remain release steps. The bounded planner remains task-only.</p><p>The operator renders exact event fields and labels approval as <strong>Approve exact event</strong>, never as a task. Every composite entry needs its own verified receipt and matching <code>condition_id</code>. Each condition reserves one immutable action; changed proposed fields require a new authorized run.</p><p><code>requestInput</code>, <code>inputRequests</code> and <code>supplyInput</code> use typed factual waits. Human responders supply through Runs; bearer clients can supply only agent-responder requests. Facts remain inspectable after completion and cannot alter scope, deadlines or action input.</p></section>
    <section className="developer-errors"><h2>Recover without guessing</h2><dl><div><dt>401 / 403</dt><dd>Check credential expiry, revocation, delegated scope, and human role. Do not blindly retry.</dd></div><div><dt>404 / 409</dt><dd>Inspect source retention, phrase, version, input/key conflicts, approval windows, and budget. A new key cannot replace a proposed condition; changed input needs a new run.</dd></div><div><dt>422</dt><dd>Correct typed inputs and factual date arithmetic. Dates must include a timezone.</dd></div><div><dt>Awaiting input</dt><dd>A nonterminal wait, not success or approval. Supply only requested facts through the authorized responder.</dd></div><div><dt>Unknown outcome</dt><dd>A remote event may exist. Do not repeat a write; an owner/admin can request bounded GET-only reconciliation. No compensation or deletion API is implemented.</dd></div><div><dt>Failed or cancelled</dt><dd>Read action results and partial-effect receipts; neither status promises rollback or whole-workflow completion.</dd></div></dl></section>
    <footer className="developer-footer"><p>Local developer implementation. SDK publication, staging identity checks, hosted deployment, and live provider verification remain separate release steps. Complete setup and local validation commands are in <code>docs/developer-agent-quickstart.md</code> in the source checkout.</p><Link href="/runs">Inspect the synthetic ledger</Link></footer>
  </main>;
}
