"""platform foundation

Revision ID: 97869c0f2a59
Revises:
Create Date: 2026-07-21 23:50:14.685829
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97869c0f2a59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('platform_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('external_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_users_external_subject'), 'platform_users', ['external_subject'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('platform_contracts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('review_context_json', sa.Text(), nullable=False),
    sa.Column('retain_document', sa.Boolean(), nullable=False),
    sa.Column('retain_source_text', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_contracts_created_by_user_id'), 'platform_contracts', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_platform_contracts_expires_at'), 'platform_contracts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_platform_contracts_organization_id'), 'platform_contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_platform_contracts_status'), 'platform_contracts', ['status'], unique=False)
    op.create_table('contract_reviews',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('quality_json', sa.Text(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['platform_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_reviews_contract_id'), 'contract_reviews', ['contract_id'], unique=True)
    op.create_index(op.f('ix_contract_reviews_organization_id'), 'contract_reviews', ['organization_id'], unique=False)
    op.create_table('document_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['platform_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_document_assets_contract_id'), 'document_assets', ['contract_id'], unique=False)
    op.create_index(op.f('ix_document_assets_organization_id'), 'document_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_assets_sha256'), 'document_assets', ['sha256'], unique=False)
    op.create_table('platform_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('contract_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['platform_contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_audit_events_action'), 'platform_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_platform_audit_events_actor_user_id'), 'platform_audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_events_contract_id'), 'platform_audit_events', ['contract_id'], unique=False)
    op.create_index(op.f('ix_platform_audit_events_created_at'), 'platform_audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_audit_events_organization_id'), 'platform_audit_events', ['organization_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('document_asset_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_step', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['platform_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_asset_id'], ['document_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_contract_id'), 'processing_jobs', ['contract_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_document_asset_id'), 'processing_jobs', ['document_asset_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_organization_id'), 'processing_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_organization_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_document_asset_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_contract_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_platform_audit_events_organization_id'), table_name='platform_audit_events')
    op.drop_index(op.f('ix_platform_audit_events_created_at'), table_name='platform_audit_events')
    op.drop_index(op.f('ix_platform_audit_events_contract_id'), table_name='platform_audit_events')
    op.drop_index(op.f('ix_platform_audit_events_actor_user_id'), table_name='platform_audit_events')
    op.drop_index(op.f('ix_platform_audit_events_action'), table_name='platform_audit_events')
    op.drop_table('platform_audit_events')
    op.drop_index(op.f('ix_document_assets_sha256'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_organization_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_contract_id'), table_name='document_assets')
    op.drop_table('document_assets')
    op.drop_index(op.f('ix_contract_reviews_organization_id'), table_name='contract_reviews')
    op.drop_index(op.f('ix_contract_reviews_contract_id'), table_name='contract_reviews')
    op.drop_table('contract_reviews')
    op.drop_index(op.f('ix_platform_contracts_status'), table_name='platform_contracts')
    op.drop_index(op.f('ix_platform_contracts_organization_id'), table_name='platform_contracts')
    op.drop_index(op.f('ix_platform_contracts_expires_at'), table_name='platform_contracts')
    op.drop_index(op.f('ix_platform_contracts_created_by_user_id'), table_name='platform_contracts')
    op.drop_table('platform_contracts')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_platform_users_external_subject'), table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
